config/routes.rb
Nodes::Engine.routes.draw do
  resources :nodes
  root :to => 'nodes#index'
  get '/node/sort/:field' => 'nodes#sort'
end

app/models/nodes/application_record.rb
module Nodes
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/nodes/node.rb
module Nodes
  class Node < ApplicationRecord
    validates :name, presence: true
    validates :date, presence: true
  end
end

app/controllers/nodes/application_controller.rb
module Nodes
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    def init
      @controller = params[:controller]
      if not %w(site user_sessions).include?(@controller)
        @object_name = @controller.singularize
        @model = @controller.singularize.split('/').map {|c| c.capitalize}.join('::').constantize if @controller
        @object = @model.find_by_id(params[:id]) if (params[:id] && @model)
      end
    end

    # ASC | DESC
    def sort
      if session[:sort] == params[:field] #change sort direction
        if session[:sort_direction] == 'DESC'
          session[:sort_direction] = 'ASC'
        else
          session[:sort_direction] = 'DESC'
        end
      else # create new sort direction
        session[:sort] = params[:field]
        session[:sort_direction] = 'ASC'
      end

      list = @model.all
      if session[:sort_direction] == 'ASC'
        list.to_a.sort! do |one, two|
          a = one.send(session[:sort])
          b = two.send(session[:sort])
          (a and b) ? a <=> b : (a ? -1 : 1)
        end
      else
        list.to_a.sort! do |one, two|
          a = one.send(session[:sort])
          b = two.send(session[:sort])
          (b and a) ? b <=> a : (b ? -1 : 1)
        end
      end
      instance_variable_set("@#{@controller}", list)
      render action: :index
    end

  end
end

app/controllers/nodes/nodes_controller.rb
require_dependency 'nodes/application_controller'

module Nodes
  class NodesController < ApplicationController
    before_action :set_node, only: [:show, :edit, :update, :destroy]

    def index
      @nodes = Node.all
    end

    def show
    end

    def new
      @node = Node.new
    end

    def edit
    end

    def create
      @node = Node.new(node_params)

      if @node.save
        redirect_to @node, notice: I18n.t(:node_was_created)
      else
        render :new
      end
    end

    def update
      if @node.update(node_params)
        redirect_to @node, notice: I18n.t(:node_was_updated)
      else
        render :edit
      end
    end

    def destroy
      @node.destroy
      redirect_to nodes_url, notice: I18n.t(:node_was_destroyed)
    end

    private
      def set_node
        @node = Node.find(params[:id])
      end
      def node_params
        params.require(:node).permit(:name)
      end

  end
end

app/helpers/nodes/application_helper.rb
module Nodes
  module ApplicationHelper
    def form_error(o)
      if o.errors.any?
        haml_tag :div, :id => 'error_explanation' do
          haml_tag :h2 do
            haml_concat t(:error_save)
          end
          haml_tag :ul do
            o.errors.full_messages.each do |msg|
              haml_tag :li do
                haml_concat msg
              end
            end
          end
        end
      end
    end

  end
end

app/views/layouts/nodes/application.haml
!!! 5
%html
  %head
    %title Nodes
    = stylesheet_link_tag 'nodes/nodes'
    = javascript_include_tag 'nodes/nodes'
    = csrf_meta_tags
    %link{:rel => 'icon', :href => image_path('nodes/favicon.ico'), :type => 'image/ico'}

  %body
    .flash
      - if flash[:notice]
        #notice= flash[:notice]
      - if flash[:alert]
        #alert= flash[:alert]

    -#%div{style: 'position:relative;height:0;padding-bottom:80.21%'}
      %iframe{ src: "https://www.youtube.com/embed/2Oy2LVaGPGE?ecver=2",
        style: "position:absolute;width:100%;height:100%;left:0",
        width: "449", height: "360", frameborder: "0", allowfullscreen: :true}

    = yield

app/views/nodes/nodes/_form.haml
= form_for @node, :html => {:class => 'node-form'} do |f|
  - form_error @node
  .field= f.text_field :name
  .actions= image_submit_tag('nodes/save.png', :title => t(:save_node) )

app/views/nodes/nodes/_form.html.haml
= form_for @node do |f|
  - if @node.errors.any?
    #error_explanation
      %h2= "#{pluralize(@node.errors.count, "error")} prohibited this node from being saved:"
      %ul
        - @node.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/nodes/nodes/edit.haml
%h1= t(:edit_node)
= render 'form'
-#.back= link_to @node.name,  @node
.back= link_to t(:nodes), nodes_path

app/views/nodes/nodes/edit.html.haml
%h1 Editing node

= render 'form'

= link_to 'Show', @node
\|
= link_to 'Back', nodes_path

app/views/nodes/nodes/index.haml
%h1= t(:nodes)
%table{class: 'nodes-list'}
  %thead
    %tr
      %th{colspan: 3}= link_to image_tag('nodes/create.png'),
        new_node_path, class: 'nodes-action', :title => t(:add_new_node)
    %tr
      %th= link_to Nodes::Node.human_attribute_name(:name),
        {action: :sort, field: :name}, class: 'nodes-sort-action', :title => t(:sort_by_name)
    -#%th= link_to Node.human_attribute_name(:date), :action => :sort, :field => :date
    -#%th= link_to Entry.human_attribute_name(:tags), :action => :sort, :field => :tag_list
  %tbody
    - @nodes.each do |node|
      %tr
      -#%td= l(node.date, :format=>:long)
      %td= link_to node.name,  node # "/entry/#{entry.title}"
      -#%td
      -#  - entry.tags.each do |tag|
      -#    =link_to tag, tag_path(tag)

app/views/nodes/nodes/new.haml
%h1= t(:new_node)
= render 'form'
.back= link_to t(:nodes), nodes_path

app/views/nodes/nodes/new.html.haml
%h1 New node

= render 'form'

= link_to 'Back', nodes_path

app/views/nodes/nodes/show.haml
.node
  %h1= link_to @node.name, edit_node_path(@node)
.back= link_to t(:nodes), nodes_path

-#.entry
  - if @entry
    .date= l(@entry.date, :format=>:long)
    .tags
      - @entry.tags.each do |tag|
        =link_to tag, tag_path(tag)
    - if @entry.author
      .author= @entry.author
    .title
      - if User.logged?(session)
        %h1= link_to @entry.name, edit_entry_path(@entry)
      - else
        %h1= @entry.name
    .text= @entry.format.html_safe
    -#.text= @entry.html
  - else
    .text No entry
  .user
    = link_to @entry.user.name, @entry.user
  .email
    = mail_to @entry.user.email


-#.line= link_to Entry::Entry.model_name.human.pluralize, entries_path

app/views/nodes/nodes/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @node.name

= link_to 'Edit', edit_node_path(@node)
\|
= link_to 'Back', nodes_path